server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AuthServiceDB
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update               # Automatic update of database schema
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#### 1000L * 60 * 5 minutes
auth-service:
  secret:
    key: 123456789

  issuer: abc-def

  expire:
    date: 300000