@echo off
setx AUTH_SERVER_PORT "WRITE YOUR_DATA"

setx AUTH_DB_PROTOCOL "WRITE YOUR_DATA"
setx AUTH_DB_IP "WRITE YOUR_DATA"
setx AUTH_DB_PORT "WRITE YOUR_DATA"
setx AUTH_DB_NAME "WRITE YOUR_DATA"
setx AUTH_DB_DRIVER "WRITE YOUR_DATA"

setx AUTH_DB_USERNAME "WRITE YOUR_DATA"
setx AUTH_DB_PASSWORD "WRITE YOUR_DATA"
setx AUTH_SECRET_KEY "WRITE YOUR_DATA"
setx AUTH_ISSUER "WRITE YOUR_DATA"

setx GITHUB_CONFIG_PATH_PROJECT "WRITE YOUR_DATA"
setx GITHUB_USERNAME "WRITE YOUR_DATA"
setx GITHUB_TOKEN_KEY "WRITE YOUR_DATA"