server:
  port: 9095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SellerServiceDB
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update                                # automatic update database schema
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

