server:
  port: 9095

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    service:
      name: seller-service
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/SellerServiceDB
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

